global using AreaCalculationLibrary.Creator;
global using AreaCalculationLibrary.FigureCalculation;
global using AreaCalculationLibrary.FigureCalculatorCreator;
global using AreaCalculationLibrary.GeneralСalculation;
